### PR TITLE
Feature/Make Send Mail a Celery Task

### PR DESCRIPTION
**Pull request by pattisdr**
# Purpose

Make Send Mail a celery task

### CODE REVIEW

**Comment by pattisdr** [comment]
@cwisecarver not sure how to test

**Comment by cwisecarver** [comment]
@pattisdr Inside your virtualenv, in the root directory of the project, run `celery worker -A project.celery.app` in another terminal (window|pane|tab) and then do something that triggers an email. Then you should see an email print out in the console that you started the celery worker in. 

There's a chance you might have to manually register that as a task somehow. I always end up putting mine in a tasks.py inside of an application, see `studies/tasks.py`. I don't remember if celery finds the tasks by looking in those modules or if it has something to do with the decorator. If you start up the celery worker with a log level of debug (`celery worker -A project.celery.app -l DEBUG`) you should see a list of the discovered tasks.
```
[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
  . project.celery.debug_task
  . studies.tasks.build_experiment
  . studies.tasks.cleanup_builds
  . studies.tasks.cleanup_checkouts
```

lmk if this doesn't help.

**Comment by pattisdr** [comment]
@cwisecarver having a hard time running celery, getting 
```
[2017-08-25 13:38:32,062: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@127.0.0.1:5672//: [Errno 61] Connection refused.
Trying again in 28.00 seconds...
```

**Comment by cwisecarver** [comment]
`brew install rabbitmq && brew services restart rabbitmq` Celery requires a broker, we generally use rabbitmq. I left that out of the instructions. I always have it installed. Sorry 😞

**Comment by cwisecarver** [comment]
lmk when you've got this working, or if I can help debug, and I'll merge it into my PR. I'm going to rebase off develop and I think I'm calling it (almost) done. No rush, if you're working on other things it's totally fine. Just didn't want it to linger. There's already one conflict 😢

**Comment by pattisdr** [comment]
thanks @cwisecarver, i ended up cherry picking this and putting it on another branch to test because i couldn't create studies here.  i'm testing successfully but having to change the context that's passed into the send_mail functions.

**Comment by pattisdr** [comment]
Closing - going to make this PR against develop once @cwisecarver's PR is merged.

**Pull request closed without merging**
