### PR TITLE
Feature/Cleanup 8

### PR DESCRIPTION
**Pull request by pattisdr**
# Purpose
Cleanup

# Changes
- [x] Changes dashboard language - removes bit about org admin being contacted
- [x]  Adds OSF_URL to defaults so forgotpassword and resend email links can be generated.

### CODE REVIEW

**Comment by pattisdr** [comment]
Forgot to commit the OSF_URL part which i was using in the passwordreset email PR @cwisecarver

**Comment by pattisdr** [comment]
thank you!

**Comment by cwisecarver** [comment]
@pattisdr FYI, when you add something that'll be coming out of an environment variable, like `OSF_URL`, we need to ping @icereval or Barrett to add that to the k8s configmap so that it'll be there when the code is deployed. Your default will work fine for staging and localdev but when we get to prod, no bueno. Looks like it should be `OSF_URL=https://osf.io`.

Dawn, in whatever your next PR is will you change `http` to `https` for that default setting? Thanks!

**Comment by pattisdr** [comment]
@cwisecarver should my i make the default OSF_URL https://osf.io and then get Michael to change staging to staging.osf.io?

**Comment by cwisecarver** [comment]
I'd make the default `https://staging.osf.io` (basically for local dev) and then ask Michael to set environment variables in the helm charts for lookit production and staging to `https://osf.io` and `https://staging.osf.io`, respectively.

**Pull request merged**
